### PR TITLE
Linux and OS X compatibility for utils.py

### PR DESCRIPTION
**Pull request by j3rwin**
- Code is untested on OS X

### CODE REVIEW

**Comment by avamsi** [comment]
Thanks for the pull, @j3rw1N!

I can't test this at the moment, so if you can confirm this is well tested (at least on Linux), I'll merge it.

**Comment by j3rwin** [comment]
Sure sir, ill test it on arch and solus now (to be sure) :)

**Comment by j3rwin** [comment]
Sorry for the delay, i had some network issues. I have tested it in arch linux(kernel 4.7.4-1) ,ubuntu 16.04,solus 1.1 and the script works fine in all.

**Comment by avamsi** [comment]
Merged. Thank you!

**Pull request merged**
