### PR TITLE
Chrome extension for flash

### PR DESCRIPTION
**Pull request by j3rwin**
-uses [http.server](https://docs.python.org/3/library/http.server.html) to create local server(on 8000 by default) which listens to GET requests.
-when clicked on download, the extension will send a GET request to the local server, where it is parsed to extract the url of file and start download

[**Loading the extension to chrome**](https://developer.chrome.com/extensions/getstarted#unpacked)

### CODE REVIEW

**Comment by avamsi** [comment]
This is a start but having a direct link you can right click on is very rare -- at least in my case.
Most of the sites use a JS download button or redirect to a new page and add the download using JS.

So I'm thinking, we should probably use the [chrome.downloads](https://developer.chrome.com/extensions/downloads) API and use Flash for large-ish resumable downloads and leave the rest to Chrome. We can pass the full path (from the Chrome download object) along with the URL. We can also use size from Chrome download object but I think passing size would need some restructuring in Flash and all that to save 1 HEAD request.

Context menu option should still probably go in. What do you think?

**Comment by j3rwin** [comment]
Yeah that would be much better :+1: and also adding a pause/resume button(to handle interruptions during download) will make it a complete download manager

**Comment by avamsi** [comment]
Hey @j3rw1N, I've added a Chrome extension that silently captures your Chrome downloads and uses Flash instead.

**Comment by j3rwin** [comment]
Awesome ,works fine thanks! no more copy-paste :+1:

**Pull request closed without merging**
